quarkus:
  devservices:
    enabled: false
  live-reload:
    enabled: true
  otel:
    logs:
      enabled: true
    traces:
      enabled: true
    exporter:
      otlp:
        endpoint: http://localhost:14317
  langchain4j:
    ollama:
      base-url: http://127.0.0.1:11434
      timeout: 60s
      chat-model:
        model-id: qwen3:1.7b
        temperature: 0.7
      embedding-model:
        model-id: embeddinggemma
    pgvector:
      dimension: 256
  datasource:
    username: ricardo-reis
    password: isThisNotAVerySecurePassword
    jdbc:
      url: jdbc:postgresql://localhost:15432/pessoa_faladora
  transaction-manager:
    default-transaction-timeout: 1000s
  hibernate-orm:
    physical-naming-strategy: me.davidgomesdev.db.RepositoryNaming
  http:
    host: 0.0.0.0
    static-dir:
      endpoint: composeResources
      path: uiResources/composeResources
rag:
  max-results: 3
  min-score: 0.7

pessoa:
  url: http://127.0.0.1:8080

